// <auto-generated />
using System;
using DhavalTailor_Wines.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DhavalTailor_Wines.Data.DWMigrations
{
    [DbContext(typeof(WinesContext))]
    partial class WinesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("DhavalTailor_Wines.Models.Wine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WineHarvest")
                        .HasColumnType("TEXT");

                    b.Property<string>("WineName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<double>("WinePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("WineYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wine_TypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Wine_TypeID");

                    b.HasIndex("WineName", "WineYear")
                        .IsUnique();

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("DhavalTailor_Wines.Models.Wine_Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("WineTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("WineTypeName")
                        .IsUnique();

                    b.ToTable("Wine_Types");
                });

            modelBuilder.Entity("DhavalTailor_Wines.Models.Wine", b =>
                {
                    b.HasOne("DhavalTailor_Wines.Models.Wine_Type", "Wine_Type")
                        .WithMany("Wines")
                        .HasForeignKey("Wine_TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wine_Type");
                });

            modelBuilder.Entity("DhavalTailor_Wines.Models.Wine_Type", b =>
                {
                    b.Navigation("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
